name = "asdsga"
url = "asdgstharaR"
description = "AGARGARGA"
licence = "Apache License 2.0"
contact_info = "RGAR"
alternatives = "RTRTHSzt"
labels = []
ibm_maintained = "- \\[ \\] This project is officially maintained by IBM Quantum"
group = "transpiler_plugin"
