name = "asriuasirufnliun"
url = "asriuasirufnliun"
description = "svsv\\`"
licence = "Apache License 2.0"
contact_info = "asrtghg"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "Chemistry", "Circuit simulator", "Converter",]
website = "argtararvea"
