name = "Blueqat"
url = "https://github.com/Blueqat/Blueqat"
description = "A quantum computing SDK"
licence = "Apache 2.0"
labels = [ "convert",]
created_at = 1678827878.864396
updated_at = 1678827878.864397
tier = "Community"
skip_tests = false
stars = 358
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.24.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231021901"
package_commit_hash = "4e3b283157b43687db4260cee6decf17fbb37608"
terra_version = "0.24.0"
timestamp = 1691162026.157952

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045462"
terra_version = "0.23.2"
timestamp = 1691162026.157957

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045386"
terra_version = "0.23.2"
timestamp = 1691162026.15796

[[styles_results]]
passed = false
style_type = "pylint"

[[coverages_results]]
passed = false
coverage_type = ""

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.21.0"
terra_version = "0.21.0"
timestamp = 1691162026.15797

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.20.2"
terra_version = "0.20.2"
timestamp = 1691162026.157973

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.20.2"
terra_version = "0.20.2"
timestamp = 1691162026.157975

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.21.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548522"
terra_version = "0.21.0"
timestamp = 1691162026.157978

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.21.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548522"
terra_version = "0.21.0"
timestamp = 1691162026.157981

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.21.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121347"
terra_version = "0.21.1"
timestamp = 1691162026.157984

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.21.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121347"
terra_version = "0.21.1"
timestamp = 1691162026.157987

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180920109"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
terra_version = "0.22.0"
timestamp = 1691162026.15799

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.21.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638641"
terra_version = "0.21.2"
timestamp = 1691162026.157993

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.21.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638640"
terra_version = "0.21.2"
timestamp = 1691162026.157996

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3319732917"
terra_version = "0.22.0"
timestamp = 1691162026.157999

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224539"
terra_version = "0.22.0"
timestamp = 1691162026.158002

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521952019"
terra_version = "0.22.2"
timestamp = 1691162026.158004

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521951991"
terra_version = "0.22.2"
timestamp = 1691162026.158007

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703336"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
terra_version = "0.23.0"
timestamp = 1691162026.15801

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703323"
terra_version = "0.22.3"
timestamp = 1691162026.158013

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703183"
terra_version = "0.22.3"
timestamp = 1691162026.158016

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994627601"
terra_version = "0.22.4"
timestamp = 1691162026.158019

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994627633"
terra_version = "0.22.4"
timestamp = 1691162026.158021

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052482988"
terra_version = "0.23.0"
timestamp = 1691162026.158024

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231021814"
terra_version = "0.23.1"
timestamp = 1691162026.158027

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231021797"
terra_version = "0.23.1"
timestamp = 1691162026.15803

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.24.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231021901"
package_commit_hash = "4e3b283157b43687db4260cee6decf17fbb37608"
terra_version = "0.24.0"
timestamp = 1691162026.158033

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045386"
terra_version = "0.23.2"
timestamp = 1691162026.158036

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045462"
terra_version = "0.23.2"
timestamp = 1691162026.158038

[configuration]
dependencies_files = [ "requirements.txt",]
extra_dependencies = [ "qiskit", "Cython", "coverage", "pylint",]
tests_command = [ "pytest",]
styles_check_command = [ "pylint -rn blueqat tests",]
coverages_check_command = [ "coverage3 -m pytest", "coverage3 report --fail-under=80",]

[configuration.language]
name = "python"
versions = [ "3.6",]
