name = "Blueqat"
url = "https://github.com/Blueqat/Blueqat"
description = "A quantum computing SDK"
licence = "Apache 2.0"
labels = [ "convert",]
created_at = 1678827878.864396
updated_at = 1678827878.864397
tier = "Community"
skip_tests = false
stars = 359
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.24.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231021901"
package_commit_hash = "4e3b283157b43687db4260cee6decf17fbb37608"
terra_version = "0.24.0"
timestamp = 1691161734.695997

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045462"
terra_version = "0.23.2"
timestamp = 1691161734.696003

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045386"
terra_version = "0.23.2"
timestamp = 1691161734.696007

[[styles_results]]
passed = false
style_type = "pylint"

[[coverages_results]]
passed = false
coverage_type = ""

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.21.0"
terra_version = "0.21.0"
timestamp = 1691161734.696021

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.20.2"
terra_version = "0.20.2"
timestamp = 1691161734.696024

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.20.2"
terra_version = "0.20.2"
timestamp = 1691161734.696027

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.21.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548522"
terra_version = "0.21.0"
timestamp = 1691161734.69603

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.21.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548522"
terra_version = "0.21.0"
timestamp = 1691161734.696033

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.21.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121347"
terra_version = "0.21.1"
timestamp = 1691161734.696037

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.21.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121347"
terra_version = "0.21.1"
timestamp = 1691161734.69604

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180920109"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
terra_version = "0.22.0"
timestamp = 1691161734.696043

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.21.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638641"
terra_version = "0.21.2"
timestamp = 1691161734.696046

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.21.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638640"
terra_version = "0.21.2"
timestamp = 1691161734.69605

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3319732917"
terra_version = "0.22.0"
timestamp = 1691161734.696053

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224539"
terra_version = "0.22.0"
timestamp = 1691161734.696056

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521952019"
terra_version = "0.22.2"
timestamp = 1691161734.696059

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521951991"
terra_version = "0.22.2"
timestamp = 1691161734.696062

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703336"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
terra_version = "0.23.0"
timestamp = 1691161734.696065

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703323"
terra_version = "0.22.3"
timestamp = 1691161734.696068

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703183"
terra_version = "0.22.3"
timestamp = 1691161734.696071

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994627601"
terra_version = "0.22.4"
timestamp = 1691161734.696075

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994627633"
terra_version = "0.22.4"
timestamp = 1691161734.696078

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052482988"
terra_version = "0.23.0"
timestamp = 1691161734.696081

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231021814"
terra_version = "0.23.1"
timestamp = 1691161734.696084

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231021797"
terra_version = "0.23.1"
timestamp = 1691161734.696087

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.24.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231021901"
package_commit_hash = "4e3b283157b43687db4260cee6decf17fbb37608"
terra_version = "0.24.0"
timestamp = 1691161734.696091

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045386"
terra_version = "0.23.2"
timestamp = 1691161734.696094

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045462"
terra_version = "0.23.2"
timestamp = 1691161734.696097

[configuration]
dependencies_files = [ "requirements.txt",]
extra_dependencies = [ "qiskit", "Cython", "coverage", "pylint",]
tests_command = [ "pytest",]
styles_check_command = [ "pylint -rn blueqat tests",]
coverages_check_command = [ "coverage3 -m pytest", "coverage3 report --fail-under=80",]

[configuration.language]
name = "python"
versions = [ "3.6",]
