name = "bosonic-qiskit"
url = "https://github.com/C2QA/bosonic-qiskit"
description = "NQI C2QA project to simulate hybrid boson-qubit systems within Qiskit."
licence = "BSD 2-Clause Simplified or FreeBSD license"
labels = [ "simulation", "physics",]
created_at = 1678827878.841977
updated_at = 1678827878.841978
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 34
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit-terra"
package_version = "0.24.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047438"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
terra_version = "0.24.0"
timestamp = 1691162026.040731

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047359"
terra_version = "0.23.2"
timestamp = 1691162026.040736

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047359"
terra_version = "0.23.2"
timestamp = 1691162026.04074

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047258"
terra_version = "0.22.0"
timestamp = 1691162026.040743

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368225482"
terra_version = "0.22.0"
timestamp = 1691162026.040749

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521953307"
terra_version = "0.22.2"
timestamp = 1691162026.040752

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937704942"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
terra_version = "0.23.0"
timestamp = 1691162026.040755

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937704855"
terra_version = "0.22.3"
timestamp = 1691162026.040758

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994629269"
terra_version = "0.22.4"
timestamp = 1691162026.040761

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052485085"
terra_version = "0.23.0"
timestamp = 1691162026.040764

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231023417"
terra_version = "0.23.1"
timestamp = 1691162026.040766

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047258"
terra_version = "0.22.0"
timestamp = 1691162026.040769

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047359"
terra_version = "0.23.2"
timestamp = 1691162026.040772

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit-terra"
package_version = "0.24.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047438"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
terra_version = "0.24.0"
timestamp = 1691162026.040775

