name = "c3"
url = "https://github.com/q-optimize/c3"
description = "The C3 package is intended to close the loop between open-loop control optimization, control pulse calibration, and model-matching based on calibration data."
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "plugin",]
created_at = 1678827878.240528
updated_at = 1678827878.240528
tier = "Community"
skip_tests = false
stars = 56
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.24.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414043772"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
terra_version = "0.24.0"
timestamp = 1691162025.937698

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit-terra"
package_version = "0.22.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3469022488"
terra_version = "0.22.2"
timestamp = 1691162025.937702

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414043735"
terra_version = "0.23.2"
timestamp = 1691162025.937705

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414043694"
terra_version = "0.23.2"
timestamp = 1691162025.937708

[[styles_results]]
passed = true
style_type = "pylint"

[[coverages_results]]
passed = true
coverage_type = ""

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.20.2"
terra_version = "0.20.2"
timestamp = 1691162025.937719

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit-terra"
package_version = "0.21.0"
terra_version = "0.21.0"
timestamp = 1691162025.937722

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.20.2"
terra_version = "0.20.2"
timestamp = 1691162025.937725

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.21.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548233"
terra_version = "0.21.0"
timestamp = 1691162025.937728

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.21.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548233"
terra_version = "0.21.0"
timestamp = 1691162025.937731

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.21.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824120979"
terra_version = "0.21.1"
timestamp = 1691162025.937734

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.21.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824120979"
terra_version = "0.21.1"
timestamp = 1691162025.937737

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180918979"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
terra_version = "0.22.0"
timestamp = 1691162025.93774

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.21.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225637724"
terra_version = "0.21.2"
timestamp = 1691162025.937743

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.21.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225637748"
terra_version = "0.21.2"
timestamp = 1691162025.937745

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368223753"
terra_version = "0.22.0"
timestamp = 1691162025.937748

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368223761"
terra_version = "0.22.0"
timestamp = 1691162025.937751

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521950511"
terra_version = "0.22.2"
timestamp = 1691162025.937754

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521950486"
terra_version = "0.22.2"
timestamp = 1691162025.937757

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937700830"
terra_version = "0.22.3"
timestamp = 1691162025.937759

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937700868"
terra_version = "0.22.3"
timestamp = 1691162025.937762

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937700942"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
terra_version = "0.23.0"
timestamp = 1691162025.937765

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994625453"
terra_version = "0.22.4"
timestamp = 1691162025.937768

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994625536"
terra_version = "0.22.4"
timestamp = 1691162025.937771

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052481181"
terra_version = "0.23.0"
timestamp = 1691162025.937773

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052481227"
terra_version = "0.23.0"
timestamp = 1691162025.937776

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231020187"
terra_version = "0.23.1"
timestamp = 1691162025.937779

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231020171"
terra_version = "0.23.1"
timestamp = 1691162025.937782

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414043735"
terra_version = "0.23.2"
timestamp = 1691162025.937785

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414043694"
terra_version = "0.23.2"
timestamp = 1691162025.937787

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.24.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414043772"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
terra_version = "0.24.0"
timestamp = 1691162025.93779

[configuration]
dependencies_files = [ "requirements.txt",]
extra_dependencies = [ "qiskit", "coverage", "pylint", "black",]
tests_command = [ "pytest -v -x -m \"not slow\" test/", "pytest -v -x -m \"slow\" test/",]
styles_check_command = [ "black --check c3/",]
coverages_check_command = [ "pytest -x -v --cov=c3 --cov-report=xml test/",]

[configuration.language]
name = "python"
versions = [ "3.7", "3.8", "3.9",]
