name = "dasliduh\\`nlkn"
url = "dasliduh\\`nlkn"
description = "sdhbaslfvlsjnfv"
licence = "Apache License 2.0"
contact_info = "fvdfzbzfbdbdzf"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "Circuit simulator",]
website = "dfvserszbz"
