name = "dense-ev"
url = "https://github.com/atlytle/dense-ev"
description = "Implements expectation value measurements in Qiskit using optimal dense grouping. Dense-ev provides an improvement of ~2^m over naive grouping and (3/2)^m over qubit-wise commuting groups. Based on arXiv:2305.11847."
licence = "Apache License 2.0"
contact_info = "atlytle@gmail.com"
alternatives = "_No response_"
affiliations = "University of Illinois at Urbana-Champaign"
labels = [ "Paper implementation",]
tier = "Community"
website = "https://github.com/atlytle/dense-ev"
styles_results = []
coverages_results = []
skip_tests = false
stars = 4
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6157309137"
package_commit_hash = "cd507adc68a96a333bc62de7ce9799a245506f25"
qiskit_version = "0.45.0"
timestamp = 1694510084.90044

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6157309137"
qiskit_version = "0.44.1"
timestamp = 1694510144.669083

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6157309137"
qiskit_version = "0.44.1"
timestamp = 1694509761.581334

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.42.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6157309137"
qiskit_version = "0.42.1"
timestamp = 1694510141.187446

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6157309137"
package_commit_hash = "cd507adc68a96a333bc62de7ce9799a245506f25"
qiskit_version = "0.45.0"
timestamp = 1694510084.90044

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.42.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6157309137"
qiskit_version = "0.42.1"
timestamp = 1694510141.187446

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6157309137"
qiskit_version = "0.44.1"
timestamp = 1694509761.581334

