name = "dense-ev"
url = "https://github.com/atlytle/dense-ev"
description = "Implements expectation value measurements in Qiskit using optimal dense grouping. Dense-ev provides an improvement of ~2^m over naive grouping and (3/2)^m over qubit-wise commuting groups. Based on arXiv:2305.11847."
licence = "Apache License 2.0"
contact_info = "atlytle@gmail.com"
alternatives = "_No response_"
affiliations = "University of Illinois at Urbana-Champaign"
labels = [ "Paper implementation",]
tier = "Community"
website = "https://github.com/atlytle/dense-ev"
styles_results = []
coverages_results = []
skip_tests = false
stars = 4
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = "01bb111cfa706658134c4481a354133bc5326f24"
qiskit_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
timestamp = 1695211429.232103

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936780501"
qiskit_version = "0.44.1"
timestamp = 1692695843.035876

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = ""
qiskit_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
timestamp = 1695211430.800435

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = ""
qiskit_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
timestamp = 1695211432.36717

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936780501"
qiskit_version = "0.44.1"
timestamp = 1692695843.035896

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.42.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936780501"
qiskit_version = "0.42.1"
timestamp = 1692695843.0359

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936780501"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "0.45.0"
timestamp = 1692695842.906331

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = "01bb111cfa706658134c4481a354133bc5326f24"
qiskit_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
timestamp = 1695211429.232103

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = ""
qiskit_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
timestamp = 1695211430.800435

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = ""
qiskit_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
timestamp = 1695211432.36717

