name = "mthree"
url = "https://github.com/Qiskit-Partners/mthree"
description = "Matrix-free Measurement Mitigation (M3)"
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = []
created_at = 1678827878.805163
updated_at = 1678827878.805164
tier = "Extensions"
styles_results = []
coverages_results = []
skip_tests = false
stars = 25
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.24.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414049677"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
terra_version = "0.24.0"
timestamp = 1691161734.404194

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit-terra"
package_version = "0.23.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231024987"
terra_version = "0.23.1"
timestamp = 1691161734.4042

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414049662"
terra_version = "0.23.2"
timestamp = 1691161734.404204

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414049585"
terra_version = "0.23.2"
timestamp = 1691161734.404207

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.21.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121650"
terra_version = "0.21.1"
timestamp = 1691161734.404214

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.21.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121650"
terra_version = "0.21.1"
timestamp = 1691161734.404218

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.21.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180921293"
terra_version = "0.21.2"
timestamp = 1691161734.404221

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180921367"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
terra_version = "0.22.0"
timestamp = 1691161734.404225

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.21.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225639689"
terra_version = "0.21.2"
timestamp = 1691161734.404228

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368226321"
terra_version = "0.22.0"
timestamp = 1691161734.404231

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368226347"
terra_version = "0.22.0"
timestamp = 1691161734.404235

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3469025244"
terra_version = "0.22.2"
timestamp = 1691161734.404238

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521954458"
terra_version = "0.22.2"
timestamp = 1691161734.404241

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937706305"
terra_version = "0.22.3"
timestamp = 1691161734.404244

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937706326"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
terra_version = "0.23.0"
timestamp = 1691161734.404248

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937706246"
terra_version = "0.22.3"
timestamp = 1691161734.404251

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994631633"
terra_version = "0.22.4"
timestamp = 1691161734.404254

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994631645"
terra_version = "0.22.4"
timestamp = 1691161734.404257

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052486650"
terra_version = "0.23.0"
timestamp = 1691161734.404261

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052486607"
terra_version = "0.23.0"
timestamp = 1691161734.404264

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231024987"
terra_version = "0.23.1"
timestamp = 1691161734.404267

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231024915"
terra_version = "0.23.1"
timestamp = 1691161734.404271

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414049585"
terra_version = "0.23.2"
timestamp = 1691161734.404274

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414049662"
terra_version = "0.23.2"
timestamp = 1691161734.404277

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.24.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414049677"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
terra_version = "0.24.0"
timestamp = 1691161734.40428

[configuration]
dependencies_files = [ "requirements.txt", "requirements-dev.txt",]
extra_dependencies = []
tests_command = [ "pytest -p no:warnings --pyargs mthree/test",]
styles_check_command = [ "pylint -rn mthree",]
coverages_check_command = []

[configuration.language]
name = "python"
versions = [ "3.7",]
