name = "pennylane-qiskit"
url = "https://github.com/PennyLaneAI/pennylane-qiskit"
description = "The PennyLane-Qiskit plugin integrates the Qiskit quantum computing framework with PennyLane's quantum machine learning capabilities"
licence = "Apache 2.0"
labels = [ "converter",]
created_at = 1678827878.782751
updated_at = 1678827878.782752
tier = "Community"
skip_tests = false
stars = 127
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045051"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
terra_version = "unknown"
timestamp = 1691242060.583171

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045004"
terra_version = "unknown"
timestamp = 1691242060.583178

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044960"
terra_version = "unknown"
timestamp = 1691242060.583182

[[styles_results]]
passed = false
style_type = "pylint"

[[coverages_results]]
passed = false
coverage_type = ""

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.21.0"
terra_version = "0.21.0"
timestamp = 1691242060.583194

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548463"
package_commit_hash = "c60d3b8e735d54c1180fe788876f3c4dacbc3cba"
terra_version = "0.22.0"
timestamp = 1691242060.583198

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.19.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548463"
terra_version = "0.19.1"
timestamp = 1691242060.583202

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.19.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548463"
terra_version = "0.19.1"
timestamp = 1691242060.583205

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "-"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039653656"
terra_version = "-"
timestamp = 1691242060.583209

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "-"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039653687"
package_commit_hash = "055fe0f9c9ca3b3b994f68ba2c7647763a29f63b"
terra_version = "-"
timestamp = 1691242060.583213

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "-"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039653655"
terra_version = "-"
timestamp = 1691242060.583216

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045051"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
terra_version = "unknown"
timestamp = 1691242060.58322

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045004"
terra_version = "unknown"
timestamp = 1691242060.583224

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044960"
terra_version = "unknown"
timestamp = 1691242060.583227

[configuration]
dependencies_files = [ "requirements.txt",]
extra_dependencies = [ "coverage", "pylint", "qiskit",]
tests_command = [ "pytest tests --tb=short",]
styles_check_command = [ "pylint -rn pennylane_qiskit tests",]
coverages_check_command = [ "python3 -m pytest tests --tb=short --cov=pennylane_qiskit --cov-report term-missing --cov-report=html:coverage_html_report",]

[configuration.language]
name = "python"
versions = [ "3.6",]
