name = "q-kernel-ops"
url = "https://github.com/Travis-S-IBM/q-kernel-ops"
description = "Code base on the paper Kernel Matrix Completion for Offline Quantum-Enhanced Machine Learning [2112.08449](https://arxiv.org/abs/2112.08449)."
licence = "Apache 2.0"
contact_info = "### Email"
alternatives = "### Alternatives"
labels = [ "Advocate mentorship project", "Machine learning",]
created_at = 1678827878.663275
updated_at = 1678827878.663276
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 3
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6010228020"
package_commit_hash = "3bd1d46c93a9d6cf2ae9e21093ce8df2b3cf52ad"
qiskit_version = "unknown"
timestamp = 1693300118.928111

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6010228020"
qiskit_version = "unknown"
timestamp = 1693300116.127535

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6010228020"
qiskit_version = "unknown"
timestamp = 1693300121.304666

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "-"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039654390"
qiskit_version = "-"
timestamp = 1692695539.680839

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "-"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039654418"
qiskit_version = "-"
timestamp = 1692695539.680842

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "-"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039654437"
package_commit_hash = "055fe0f9c9ca3b3b994f68ba2c7647763a29f63b"
qiskit_version = "-"
timestamp = 1692695539.680846

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6010228020"
qiskit_version = "unknown"
timestamp = 1693300121.304666

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6010228020"
package_commit_hash = "3bd1d46c93a9d6cf2ae9e21093ce8df2b3cf52ad"
qiskit_version = "unknown"
timestamp = 1693300118.928111

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6010228020"
qiskit_version = "unknown"
timestamp = 1693300116.127535

