name = "q-kernel-ops"
url = "https://github.com/Travis-S-IBM/q-kernel-ops"
description = "Code base on the paper Kernel Matrix Completion for Offline Quantum-Enhanced Machine Learning [2112.08449](https://arxiv.org/abs/2112.08449)."
licence = "Apache 2.0"
contact_info = "### Email"
alternatives = "### Alternatives"
labels = [ "Advocate mentorship project", "Machine learning",]
created_at = 1678827878.663275
updated_at = 1678827878.663276
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 3
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "development"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6250084217/job/run_tests"
package_commit_hash = "01bb111cfa706658134c4481a354133bc5326f24"
qiskit_version = "development"
timestamp = 1695221033.870033

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6250084217/job/run_tests"
package_commit_hash = ""
qiskit_version = "0.44.1"
timestamp = 1695220982.421416

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.25.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6250084217/job/run_tests"
package_commit_hash = ""
qiskit_version = "0.25.1"
timestamp = 1695220990.78588

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "-"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039654390"
qiskit_version = "-"
timestamp = 1692695539.680839

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "-"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039654418"
qiskit_version = "-"
timestamp = 1692695539.680842

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "-"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3039654437"
package_commit_hash = "055fe0f9c9ca3b3b994f68ba2c7647763a29f63b"
qiskit_version = "-"
timestamp = 1692695539.680846

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936780975"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "unknown"
timestamp = 1692695539.680853

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936780975"
qiskit_version = "unknown"
timestamp = 1692695539.680857

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "unknown"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936780975"
qiskit_version = "unknown"
timestamp = 1692695539.514552

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6250084217/job/run_tests"
package_commit_hash = ""
qiskit_version = "0.44.1"
timestamp = 1695220982.421416

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.25.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6250084217/job/run_tests"
package_commit_hash = ""
qiskit_version = "0.25.1"
timestamp = 1695220990.78588

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "development"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6250084217/job/run_tests"
package_commit_hash = "01bb111cfa706658134c4481a354133bc5326f24"
qiskit_version = "development"
timestamp = 1695221033.870033

