name = "qiskit-classroom-converter"
url = "https://github.com/KMU-quantum-classroom/qiskit-classroom-converter"
description = "Convert quantum circuits, matrices, and bra-ket strings. This converter includes the following conversion functions: quantum circuit to bra-ket notation, quantum circuit to matrix, matrix to quantum circuit, bra-ket notation to matrix"
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
affiliations = "_No response_"
labels = [ "Converter",]
tier = "Community"
website = "https://github.com/KMU-quantum-classroom"
styles_results = []
coverages_results = []
skip_tests = false
stars = 1
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6010225619"
package_commit_hash = "3bd1d46c93a9d6cf2ae9e21093ce8df2b3cf52ad"
qiskit_version = "0.45.0"
timestamp = 1693300542.519383

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6010225619"
qiskit_version = "0.44.1"
timestamp = 1693300620.271437

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6010225619"
qiskit_version = "0.44.1"
timestamp = 1693300185.236468

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6010225619"
qiskit_version = "0.44.1"
timestamp = 1693300617.589624

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936778455"
qiskit_version = "0.44.0"
timestamp = 1692695810.332834

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6010225619"
package_commit_hash = "3bd1d46c93a9d6cf2ae9e21093ce8df2b3cf52ad"
qiskit_version = "0.45.0"
timestamp = 1693300542.519383

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6010225619"
qiskit_version = "0.44.1"
timestamp = 1693300185.236468

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6010225619"
qiskit_version = "0.44.1"
timestamp = 1693300617.589624

