name = "Qiskit Nature PySCF"
url = "https://github.com/qiskit-community/qiskit-nature-pyscf"
description = "Qiskit Nature PySCF is a third-party integration plugin of Qiskit Nature and PySCF."
licence = "Apache License 2.0"
contact_info = "_No response_"
alternatives = "_No response_"
labels = [ "plugin", "chemistry",]
created_at = 1678827878.723733
updated_at = 1678827878.723734
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 13
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit-terra"
package_version = "0.24.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047970"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
terra_version = "0.24.0"
timestamp = 1691239329.608162

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047863"
terra_version = "0.23.2"
timestamp = 1691239329.608169

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047863"
terra_version = "0.23.2"
timestamp = 1691239329.608173

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047797"
terra_version = "0.23.2"
timestamp = 1691239329.608176

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705234"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
terra_version = "0.23.0"
timestamp = 1691239329.608184

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705147"
terra_version = "0.22.3"
timestamp = 1691239329.608188

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705182"
terra_version = "0.22.3"
timestamp = 1691239329.608191

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994629837"
terra_version = "0.22.4"
timestamp = 1691239329.608195

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.0rc1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994629761"
terra_version = "0.23.0rc1"
timestamp = 1691239329.608198

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052485540"
terra_version = "0.23.0"
timestamp = 1691239329.608202

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052485468"
terra_version = "0.23.0"
timestamp = 1691239329.608205

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231023779"
terra_version = "0.23.1"
timestamp = 1691239329.608209

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231023690"
terra_version = "0.23.1"
timestamp = 1691239329.608212

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047797"
terra_version = "0.23.2"
timestamp = 1691239329.608216

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047863"
terra_version = "0.23.2"
timestamp = 1691239329.608219

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit-terra"
package_version = "0.24.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414047970"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
terra_version = "0.24.0"
timestamp = 1691239329.608223

