name = "qiskit-ionq"
url = "https://github.com/Qiskit-Partners/qiskit-ionq"
description = "Project contains a provider that allows access to IonQ ion trap quantum systems."
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "Provider", "Partner",]
created_at = 1670427446.011674
updated_at = 1670427446.011675
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 30
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = "01bb111cfa706658134c4481a354133bc5326f24"
qiskit_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
timestamp = 1695211472.377427

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
qiskit_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
timestamp = 1695211474.989714

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = ""
qiskit_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
timestamp = 1695211474.089174

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = ""
qiskit_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
timestamp = 1695211475.798189

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121621"
qiskit_version = "0.37.1"
timestamp = 1692696164.80215

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.37.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121621"
qiskit_version = "0.37.1"
timestamp = 1692696164.802153

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180921277"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
qiskit_version = "0.39.0"
timestamp = 1692696164.802156

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225639640"
qiskit_version = "0.38.0"
timestamp = 1692696164.802159

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225639611"
qiskit_version = "0.38.0"
timestamp = 1692696164.802162

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368226131"
qiskit_version = "0.39.0"
timestamp = 1692696164.802165

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368226160"
qiskit_version = "0.39.0"
timestamp = 1692696164.802168

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521954337"
qiskit_version = "0.39.2"
timestamp = 1692696164.80217

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521954292"
qiskit_version = "0.39.2"
timestamp = 1692696164.802173

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3628097663"
qiskit_version = "0.39.4"
timestamp = 1692696164.802176

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3628097776"
package_commit_hash = "0df0d29fc44fb571e38530d20743a6e70e230865"
qiskit_version = "0.40.0"
timestamp = 1692696164.802179

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3628097716"
qiskit_version = "0.39.4"
timestamp = 1692696164.802182

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781939"
qiskit_version = "0.44.1"
timestamp = 1692696164.802187

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781939"
qiskit_version = ""
timestamp = 1692696164.80219

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936781939"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "0.45.0"
timestamp = 1692696164.635205

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = "01bb111cfa706658134c4481a354133bc5326f24"
qiskit_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
timestamp = 1695211472.377427

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = ""
qiskit_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
timestamp = 1695211474.089174

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = ""
qiskit_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta"
timestamp = 1695211475.798189

[configuration]
dependencies_files = [ "requirements.txt", "requirements-test.txt",]
extra_dependencies = []
tests_command = [ "python setup.py test",]
styles_check_command = [ "pylint -rn --rcfile=./.pylintrc qiskit_ionq test",]
coverages_check_command = []

[configuration.language]
name = "python"
versions = [ "3.7",]
