name = "qiskit-rigetti"
url = "https://github.com/rigetti/qiskit-rigetti"
description = "Rigetti Provider for Qiskit"
licence = "Apache 2.0"
labels = [ "provider",]
created_at = 1678827878.136911
updated_at = 1678827878.136912
tier = "Community"
skip_tests = false
stars = 7
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.24.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046008"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
terra_version = "0.24.0"
timestamp = 1691161734.57665

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045904"
terra_version = "0.23.2"
timestamp = 1691161734.576657

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045863"
terra_version = "0.23.2"
timestamp = 1691161734.576661

[[styles_results]]
passed = false
style_type = "pylint"

[[coverages_results]]
passed = false
coverage_type = ""

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.20.2"
terra_version = "0.20.2"
timestamp = 1691161734.576675

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.20.2"
terra_version = "0.20.2"
timestamp = 1691161734.576679

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.21.0"
terra_version = "0.21.0"
timestamp = 1691161734.576682

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.21.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548565"
terra_version = "0.21.0"
timestamp = 1691161734.576754

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.21.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548565"
terra_version = "0.21.0"
timestamp = 1691161734.57676

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.21.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121452"
terra_version = "0.21.1"
timestamp = 1691161734.576763

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.21.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121452"
terra_version = "0.21.1"
timestamp = 1691161734.576767

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180920336"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
terra_version = "0.22.0"
timestamp = 1691161734.576771

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.21.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638837"
terra_version = "0.21.2"
timestamp = 1691161734.576774

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.21.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225638860"
terra_version = "0.21.2"
timestamp = 1691161734.576777

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224732"
terra_version = "0.22.0"
timestamp = 1691161734.576781

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224678"
terra_version = "0.22.0"
timestamp = 1691161734.576784

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521952331"
terra_version = "0.22.2"
timestamp = 1691161734.576788

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521952362"
terra_version = "0.22.2"
timestamp = 1691161734.576791

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703796"
terra_version = "0.22.3"
timestamp = 1691161734.576795

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703897"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
terra_version = "0.23.0"
timestamp = 1691161734.576798

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937703767"
terra_version = "0.22.3"
timestamp = 1691161734.576802

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994628005"
terra_version = "0.22.4"
timestamp = 1691161734.576805

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994627910"
terra_version = "0.22.4"
timestamp = 1691161734.576809

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052483522"
terra_version = "0.23.0"
timestamp = 1691161734.576812

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052483440"
terra_version = "0.23.0"
timestamp = 1691161734.576816

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231022161"
terra_version = "0.23.1"
timestamp = 1691161734.576819

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231022210"
terra_version = "0.23.1"
timestamp = 1691161734.576822

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045863"
terra_version = "0.23.2"
timestamp = 1691161734.576826

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.24.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046008"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
terra_version = "0.24.0"
timestamp = 1691161734.576829

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414045904"
terra_version = "0.23.2"
timestamp = 1691161734.576833

[configuration]
dependencies_files = []
extra_dependencies = [ "qiskit", "coverage", "pylint", "numpy==1.*,>=1.20.1", "pyquil==3.*,>=3.0.0", "black==20.*,>=20.8.0.b1", "flake8==3.*,>=3.8.1", "mypy==0.*,>=0.800.0", "pip-licenses==3.*,>=3.5.1", "pytest==6.*,>=6.2.2", "pytest-cov==2.*,>=2.11.1", "pytest-httpx==0.*,>=0.9.0", "pytest-mock==3.*,>=3.6.1",]
tests_command = [ "pytest",]
styles_check_command = [ "pylint -rn qiskit_rigetti tests",]
coverages_check_command = [ "coverage3 -m pytest", "coverage3 report --fail-under=80",]

[configuration.language]
name = "python"
versions = [ "3.6",]
