name = "qiskit-alt"
url = "https://github.com/Qiskit-Extensions/qiskit-alt"
description = "Python package uses a backend written in Julia to implement high performance features for standard Qiskit."
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "julia",]
created_at = 1678827878.588404
updated_at = 1678827878.588404
tier = "Extensions"
styles_results = []
coverages_results = []
skip_tests = false
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.24.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414048422"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
terra_version = "0.24.0"
timestamp = 1691239329.303098

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231023996"
terra_version = "0.23.1"
timestamp = 1691239329.303105

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414048325"
terra_version = "0.23.2"
timestamp = 1691239329.303109

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.21.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121702"
terra_version = "0.21.1"
timestamp = 1691239329.303116

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.21.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121702"
terra_version = "0.21.1"
timestamp = 1691239329.30312

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180920833"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
terra_version = "0.22.0"
timestamp = 1691239329.303124

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.21.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225639231"
terra_version = "0.21.2"
timestamp = 1691239329.303127

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.21.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225639249"
terra_version = "0.21.2"
timestamp = 1691239329.30313

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368225683"
terra_version = "0.22.0"
timestamp = 1691239329.303134

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368225703"
terra_version = "0.22.0"
timestamp = 1691239329.303137

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521953654"
terra_version = "0.22.2"
timestamp = 1691239329.303141

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521953616"
terra_version = "0.22.2"
timestamp = 1691239329.303144

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3881842278"
terra_version = "0.22.3"
timestamp = 1691239329.303148

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705487"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
terra_version = "0.23.0"
timestamp = 1691239329.303151

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937705437"
terra_version = "0.22.3"
timestamp = 1691239329.303155

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994630330"
terra_version = "0.22.4"
timestamp = 1691239329.303159

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994630381"
terra_version = "0.22.4"
timestamp = 1691239329.303162

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052485690"
terra_version = "0.23.0"
timestamp = 1691239329.303165

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052485740"
terra_version = "0.23.0"
timestamp = 1691239329.303169

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231023996"
terra_version = "0.23.1"
timestamp = 1691239329.303172

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231023911"
terra_version = "0.23.1"
timestamp = 1691239329.303176

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.24.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414048422"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
terra_version = "0.24.0"
timestamp = 1691239329.303179

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414048325"
terra_version = "0.23.2"
timestamp = 1691239329.303183

[configuration]
dependencies_files = [ "requirements.txt", "requirements-dev.txt",]
extra_dependencies = []
tests_command = [ "pytest -p no:warnings --pyargs test",]
styles_check_command = [ "pylint -rn src",]
coverages_check_command = []

[configuration.language]
name = "python"
versions = [ "3.7",]
