name = "qiskit-ionq"
url = "https://github.com/Qiskit-Partners/qiskit-ionq"
description = "Project contains a provider that allows access to IonQ ion trap quantum systems."
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "provider", "partner",]
created_at = 1670427446.011674
updated_at = 1670427446.011675
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 29
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3628097776"
package_commit_hash = "0df0d29fc44fb571e38530d20743a6e70e230865"
terra_version = "0.23.0"
timestamp = 1691162026.214084

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3628097716"
terra_version = "0.22.3"
timestamp = 1691162026.214089

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3628097716"
terra_version = "0.22.3"
timestamp = 1691162026.214091

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3628097663"
terra_version = "0.22.3"
timestamp = 1691162026.214094

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.21.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121621"
terra_version = "0.21.1"
timestamp = 1691162026.2141

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.21.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121621"
terra_version = "0.21.1"
timestamp = 1691162026.214103

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180921277"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
terra_version = "0.22.0"
timestamp = 1691162026.214106

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.21.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225639640"
terra_version = "0.21.2"
timestamp = 1691162026.214109

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.21.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225639611"
terra_version = "0.21.2"
timestamp = 1691162026.214112

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368226131"
terra_version = "0.22.0"
timestamp = 1691162026.214115

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368226160"
terra_version = "0.22.0"
timestamp = 1691162026.214118

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521954337"
terra_version = "0.22.2"
timestamp = 1691162026.21412

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521954292"
terra_version = "0.22.2"
timestamp = 1691162026.214123

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3628097663"
terra_version = "0.22.3"
timestamp = 1691162026.214126

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3628097776"
package_commit_hash = "0df0d29fc44fb571e38530d20743a6e70e230865"
terra_version = "0.23.0"
timestamp = 1691162026.214129

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3628097716"
terra_version = "0.22.3"
timestamp = 1691162026.214132

[configuration]
dependencies_files = [ "requirements.txt", "requirements-test.txt",]
extra_dependencies = []
tests_command = [ "python setup.py test",]
styles_check_command = [ "pylint -rn --rcfile=./.pylintrc qiskit_ionq test",]
coverages_check_command = []

[configuration.language]
name = "python"
versions = [ "3.7",]
