name = "QPong"
url = "https://github.com/HuangJunye/QPong"
description = "A quantum version of the classic game Pong built with Qiskit and PyGame"
licence = "Apache 2.0"
contact_info = "ukskosana@gmail.com"
alternatives = "_No response_"
labels = [ "game",]
created_at = 1678827877.979398
updated_at = 1678827877.979398
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 110
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.24.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046211"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
terra_version = "0.24.0"
timestamp = 1691242060.459232

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046214"
terra_version = "0.23.2"
timestamp = 1691242060.459239

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.20.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046210"
terra_version = "0.20.1"
timestamp = 1691242060.459243

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.20.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2998938879"
terra_version = "0.20.1"
timestamp = 1691242060.459249

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180920605"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
terra_version = "0.22.0"
timestamp = 1691242060.459254

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.21.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225639040"
terra_version = "0.21.2"
timestamp = 1691242060.459257

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224830"
terra_version = "0.22.0"
timestamp = 1691242060.459261

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521952730"
terra_version = "0.22.2"
timestamp = 1691242060.459264

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937704251"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
terra_version = "0.23.0"
timestamp = 1691242060.459268

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937704190"
terra_version = "0.22.3"
timestamp = 1691242060.459271

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994628345"
terra_version = "0.22.4"
timestamp = 1691242060.459275

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052484060"
terra_version = "0.23.0"
timestamp = 1691242060.459278

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231022588"
terra_version = "0.23.1"
timestamp = 1691242060.459281

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit-terra"
package_version = "0.24.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046211"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
terra_version = "0.24.0"
timestamp = 1691242060.459285

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit-terra"
package_version = "0.20.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046210"
terra_version = "0.20.1"
timestamp = 1691242060.459289

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046214"
terra_version = "0.23.2"
timestamp = 1691242060.459292

[configuration]
dependencies_files = [ "requirements.txt", "requirements-dev.txt",]
extra_dependencies = [ "pytest",]
tests_command = [ "pytest",]
styles_check_command = [ "pylint -rn qpong tests",]
coverages_check_command = [ "coverage3 run -m pytest", "coverage3 report --fail-under=80",]

[configuration.language]
name = "python"
versions = [ "3.9",]
