name = "QPong"
url = "https://github.com/HuangJunye/QPong"
description = "A quantum version of the classic game Pong built with Qiskit and PyGame"
licence = "Apache 2.0"
contact_info = "ukskosana@gmail.com"
alternatives = "_No response_"
labels = [ "Game",]
created_at = 1678827877.979398
updated_at = 1678827877.979398
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 110
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "py39: astroid==2.6.6,attrs==23.1.0,black==22.3.0,certifi==2023.7.22,cffi==1.15.1,charset-normalizer==3.2.0,click==8.1.7,coverage==5.5,cryptography==41.0.4,dill==0.3.7,distlib==0.3.7,filelock==3.12.4,idna==3.4,iniconfig==2.0.0,isort==5.12.0,lazy-object-proxy==1.9.0,mccabe==0.6.1,mpmath==1.3.0,mypy-extensions==1.0.0,numpy==1.26.0,packaging==23.1,pathspec==0.11.2,pbr==5.11.1,pip==23.2.1,platformdirs==3.10.0,pluggy==0.13.1,ply==3.11,psutil==5.9.5,py==1.11.0,pycparser==2.21,pygame==2.1.2,pylint==2.9.5,pyspnego==0.9.2,pytest==6.2.4,python-constraint==1.4.0,python-dateutil==2.8.2,qiskit-aer==0.10.4,qiskit-ibmq-provider==0.19.1,qiskit-ignis==0.7.0,qiskit-terra @ git+https://github.com/Qiskit/qiskit@01bb111cfa706658134c4481a354133bc5326f24,requests==2.31.0,requests-ntlm==1.2.0,retworkx==0.13.1,rustworkx==0.13.1,scipy==1.11.2,setuptools==68.2.0,six==1.16.0,stevedore==5.1.0,symengine==0.9.2,sympy==1.12,toml==0.10.2,tomli==2.0.1,tox==3.24.0,tweedledum==1.1.1,typing_extensions==4.8.0,urllib3==2.0.5,virtualenv==20.24.5,websocket-client==1.6.3,websockets==11.0.3,wheel==0.41.2,wrapt==1.12.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = "01bb111cfa706658134c4481a354133bc5326f24"
qiskit_version = "py39: astroid==2.6.6,attrs==23.1.0,black==22.3.0,certifi==2023.7.22,cffi==1.15.1,charset-normalizer==3.2.0,click==8.1.7,coverage==5.5,cryptography==41.0.4,dill==0.3.7,distlib==0.3.7,filelock==3.12.4,idna==3.4,iniconfig==2.0.0,isort==5.12.0,lazy-object-proxy==1.9.0,mccabe==0.6.1,mpmath==1.3.0,mypy-extensions==1.0.0,numpy==1.26.0,packaging==23.1,pathspec==0.11.2,pbr==5.11.1,pip==23.2.1,platformdirs==3.10.0,pluggy==0.13.1,ply==3.11,psutil==5.9.5,py==1.11.0,pycparser==2.21,pygame==2.1.2,pylint==2.9.5,pyspnego==0.9.2,pytest==6.2.4,python-constraint==1.4.0,python-dateutil==2.8.2,qiskit-aer==0.10.4,qiskit-ibmq-provider==0.19.1,qiskit-ignis==0.7.0,qiskit-terra @ git+https://github.com/Qiskit/qiskit@01bb111cfa706658134c4481a354133bc5326f24,requests==2.31.0,requests-ntlm==1.2.0,retworkx==0.13.1,rustworkx==0.13.1,scipy==1.11.2,setuptools==68.2.0,six==1.16.0,stevedore==5.1.0,symengine==0.9.2,sympy==1.12,toml==0.10.2,tomli==2.0.1,tox==3.24.0,tweedledum==1.1.1,typing_extensions==4.8.0,urllib3==2.0.5,virtualenv==20.24.5,websocket-client==1.6.3,websockets==11.0.3,wheel==0.41.2,wrapt==1.12.1"
timestamp = 1695211415.422492

[[tests_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "py39: astroid==2.6.6,attrs==23.1.0,black==22.3.0,certifi==2023.7.22,cffi==1.15.1,charset-normalizer==3.2.0,click==8.1.7,coverage==5.5,cryptography==41.0.4,dill==0.3.7,distlib==0.3.7,filelock==3.12.4,idna==3.4,iniconfig==2.0.0,isort==5.12.0,lazy-object-proxy==1.9.0,mccabe==0.6.1,mpmath==1.3.0,mypy-extensions==1.0.0,numpy==1.26.0,packaging==23.1,pathspec==0.11.2,pbr==5.11.1,pip==23.2.1,platformdirs==3.10.0,pluggy==0.13.1,ply==3.11,psutil==5.9.5,py==1.11.0,pycparser==2.21,pygame==2.1.2,pylint==2.9.5,pyspnego==0.9.2,pytest==6.2.4,python-constraint==1.4.0,python-dateutil==2.8.2,qiskit==0.44.1,qiskit-aer==0.10.4,qiskit-ibmq-provider==0.19.1,qiskit-ignis==0.7.0,qiskit-terra==0.25.1,requests==2.31.0,requests-ntlm==1.2.0,retworkx==0.13.1,rustworkx==0.13.1,scipy==1.11.2,setuptools==68.2.0,six==1.16.0,stevedore==5.1.0,symengine==0.9.2,sympy==1.12,toml==0.10.2,tomli==2.0.1,tox==3.24.0,tweedledum==1.1.1,typing_extensions==4.8.0,urllib3==2.0.5,virtualenv==20.24.5,websocket-client==1.6.3,websockets==11.0.3,wheel==0.41.2,wrapt==1.12.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = ""
qiskit_version = "py39: astroid==2.6.6,attrs==23.1.0,black==22.3.0,certifi==2023.7.22,cffi==1.15.1,charset-normalizer==3.2.0,click==8.1.7,coverage==5.5,cryptography==41.0.4,dill==0.3.7,distlib==0.3.7,filelock==3.12.4,idna==3.4,iniconfig==2.0.0,isort==5.12.0,lazy-object-proxy==1.9.0,mccabe==0.6.1,mpmath==1.3.0,mypy-extensions==1.0.0,numpy==1.26.0,packaging==23.1,pathspec==0.11.2,pbr==5.11.1,pip==23.2.1,platformdirs==3.10.0,pluggy==0.13.1,ply==3.11,psutil==5.9.5,py==1.11.0,pycparser==2.21,pygame==2.1.2,pylint==2.9.5,pyspnego==0.9.2,pytest==6.2.4,python-constraint==1.4.0,python-dateutil==2.8.2,qiskit==0.44.1,qiskit-aer==0.10.4,qiskit-ibmq-provider==0.19.1,qiskit-ignis==0.7.0,qiskit-terra==0.25.1,requests==2.31.0,requests-ntlm==1.2.0,retworkx==0.13.1,rustworkx==0.13.1,scipy==1.11.2,setuptools==68.2.0,six==1.16.0,stevedore==5.1.0,symengine==0.9.2,sympy==1.12,toml==0.10.2,tomli==2.0.1,tox==3.24.0,tweedledum==1.1.1,typing_extensions==4.8.0,urllib3==2.0.5,virtualenv==20.24.5,websocket-client==1.6.3,websockets==11.0.3,wheel==0.41.2,wrapt==1.12.1"
timestamp = 1695211416.922667

[[tests_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "py39: astroid==2.6.6,attrs==23.1.0,black==22.3.0,certifi==2023.7.22,cffi==1.15.1,charset-normalizer==3.2.0,click==8.1.7,coverage==5.5,cryptography==41.0.4,dill==0.3.7,distlib==0.3.7,filelock==3.12.4,idna==3.4,iniconfig==2.0.0,isort==5.12.0,lazy-object-proxy==1.9.0,mccabe==0.6.1,mpmath==1.3.0,mypy-extensions==1.0.0,numpy==1.26.0,packaging==23.1,pathspec==0.11.2,pbr==5.11.1,pip==23.2.1,platformdirs==3.10.0,pluggy==0.13.1,ply==3.11,psutil==5.9.5,py==1.11.0,pycparser==2.21,pygame==2.1.2,pylint==2.9.5,pyspnego==0.9.2,pytest==6.2.4,python-constraint==1.4.0,python-dateutil==2.8.2,qiskit==0.36.1,qiskit-aer==0.10.4,qiskit-ibmq-provider==0.19.1,qiskit-ignis==0.7.0,qiskit-terra==0.20.1,requests==2.31.0,requests-ntlm==1.2.0,retworkx==0.13.1,rustworkx==0.13.1,scipy==1.11.2,setuptools==68.2.0,six==1.16.0,stevedore==5.1.0,symengine==0.10.0,sympy==1.12,toml==0.10.2,tomli==2.0.1,tox==3.24.0,tweedledum==1.1.1,typing_extensions==4.8.0,urllib3==2.0.5,virtualenv==20.24.5,websocket-client==1.6.3,websockets==11.0.3,wheel==0.41.2,wrapt==1.12.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = ""
qiskit_version = "py39: astroid==2.6.6,attrs==23.1.0,black==22.3.0,certifi==2023.7.22,cffi==1.15.1,charset-normalizer==3.2.0,click==8.1.7,coverage==5.5,cryptography==41.0.4,dill==0.3.7,distlib==0.3.7,filelock==3.12.4,idna==3.4,iniconfig==2.0.0,isort==5.12.0,lazy-object-proxy==1.9.0,mccabe==0.6.1,mpmath==1.3.0,mypy-extensions==1.0.0,numpy==1.26.0,packaging==23.1,pathspec==0.11.2,pbr==5.11.1,pip==23.2.1,platformdirs==3.10.0,pluggy==0.13.1,ply==3.11,psutil==5.9.5,py==1.11.0,pycparser==2.21,pygame==2.1.2,pylint==2.9.5,pyspnego==0.9.2,pytest==6.2.4,python-constraint==1.4.0,python-dateutil==2.8.2,qiskit==0.36.1,qiskit-aer==0.10.4,qiskit-ibmq-provider==0.19.1,qiskit-ignis==0.7.0,qiskit-terra==0.20.1,requests==2.31.0,requests-ntlm==1.2.0,retworkx==0.13.1,rustworkx==0.13.1,scipy==1.11.2,setuptools==68.2.0,six==1.16.0,stevedore==5.1.0,symengine==0.10.0,sympy==1.12,toml==0.10.2,tomli==2.0.1,tox==3.24.0,tweedledum==1.1.1,typing_extensions==4.8.0,urllib3==2.0.5,virtualenv==20.24.5,websocket-client==1.6.3,websockets==11.0.3,wheel==0.41.2,wrapt==1.12.1"
timestamp = 1695211418.435051

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.36.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2998938879"
qiskit_version = "0.36.1"
timestamp = 1692696186.206015

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180920605"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
qiskit_version = "0.39.0"
timestamp = 1692696186.206018

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.38.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225639040"
qiskit_version = "0.38.0"
timestamp = 1692696186.206021

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368224830"
qiskit_version = "0.39.0"
timestamp = 1692696186.206024

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521952730"
qiskit_version = "0.39.2"
timestamp = 1692696186.206027

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937704251"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
qiskit_version = "0.40.0"
timestamp = 1692696186.206031

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937704190"
qiskit_version = "0.39.4"
timestamp = 1692696186.206034

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.39.5"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994628345"
qiskit_version = "0.39.5"
timestamp = 1692696186.206037

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.40.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052484060"
qiskit_version = "0.40.0"
timestamp = 1692696186.20604

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.41.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231022588"
qiskit_version = "0.41.0"
timestamp = 1692696186.206043

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.43.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046211"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
qiskit_version = "0.43.0"
timestamp = 1692696186.206046

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.41.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414046214"
qiskit_version = "0.41.1"
timestamp = 1692696186.206049

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936782109"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "0.45.0"
timestamp = 1692696186.206055

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936782109"
qiskit_version = "0.44.1"
timestamp = 1692696186.206058

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "0.36.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936782109"
qiskit_version = "0.36.1"
timestamp = 1692696186.074956

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "py39: astroid==2.6.6,attrs==23.1.0,black==22.3.0,certifi==2023.7.22,cffi==1.15.1,charset-normalizer==3.2.0,click==8.1.7,coverage==5.5,cryptography==41.0.4,dill==0.3.7,distlib==0.3.7,filelock==3.12.4,idna==3.4,iniconfig==2.0.0,isort==5.12.0,lazy-object-proxy==1.9.0,mccabe==0.6.1,mpmath==1.3.0,mypy-extensions==1.0.0,numpy==1.26.0,packaging==23.1,pathspec==0.11.2,pbr==5.11.1,pip==23.2.1,platformdirs==3.10.0,pluggy==0.13.1,ply==3.11,psutil==5.9.5,py==1.11.0,pycparser==2.21,pygame==2.1.2,pylint==2.9.5,pyspnego==0.9.2,pytest==6.2.4,python-constraint==1.4.0,python-dateutil==2.8.2,qiskit-aer==0.10.4,qiskit-ibmq-provider==0.19.1,qiskit-ignis==0.7.0,qiskit-terra @ git+https://github.com/Qiskit/qiskit@01bb111cfa706658134c4481a354133bc5326f24,requests==2.31.0,requests-ntlm==1.2.0,retworkx==0.13.1,rustworkx==0.13.1,scipy==1.11.2,setuptools==68.2.0,six==1.16.0,stevedore==5.1.0,symengine==0.9.2,sympy==1.12,toml==0.10.2,tomli==2.0.1,tox==3.24.0,tweedledum==1.1.1,typing_extensions==4.8.0,urllib3==2.0.5,virtualenv==20.24.5,websocket-client==1.6.3,websockets==11.0.3,wheel==0.41.2,wrapt==1.12.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = "01bb111cfa706658134c4481a354133bc5326f24"
qiskit_version = "py39: astroid==2.6.6,attrs==23.1.0,black==22.3.0,certifi==2023.7.22,cffi==1.15.1,charset-normalizer==3.2.0,click==8.1.7,coverage==5.5,cryptography==41.0.4,dill==0.3.7,distlib==0.3.7,filelock==3.12.4,idna==3.4,iniconfig==2.0.0,isort==5.12.0,lazy-object-proxy==1.9.0,mccabe==0.6.1,mpmath==1.3.0,mypy-extensions==1.0.0,numpy==1.26.0,packaging==23.1,pathspec==0.11.2,pbr==5.11.1,pip==23.2.1,platformdirs==3.10.0,pluggy==0.13.1,ply==3.11,psutil==5.9.5,py==1.11.0,pycparser==2.21,pygame==2.1.2,pylint==2.9.5,pyspnego==0.9.2,pytest==6.2.4,python-constraint==1.4.0,python-dateutil==2.8.2,qiskit-aer==0.10.4,qiskit-ibmq-provider==0.19.1,qiskit-ignis==0.7.0,qiskit-terra @ git+https://github.com/Qiskit/qiskit@01bb111cfa706658134c4481a354133bc5326f24,requests==2.31.0,requests-ntlm==1.2.0,retworkx==0.13.1,rustworkx==0.13.1,scipy==1.11.2,setuptools==68.2.0,six==1.16.0,stevedore==5.1.0,symengine==0.9.2,sympy==1.12,toml==0.10.2,tomli==2.0.1,tox==3.24.0,tweedledum==1.1.1,typing_extensions==4.8.0,urllib3==2.0.5,virtualenv==20.24.5,websocket-client==1.6.3,websockets==11.0.3,wheel==0.41.2,wrapt==1.12.1"
timestamp = 1695211415.422492

[[historical_test_results]]
passed = false
test_type = "stable"
package = "qiskit"
package_version = "py39: astroid==2.6.6,attrs==23.1.0,black==22.3.0,certifi==2023.7.22,cffi==1.15.1,charset-normalizer==3.2.0,click==8.1.7,coverage==5.5,cryptography==41.0.4,dill==0.3.7,distlib==0.3.7,filelock==3.12.4,idna==3.4,iniconfig==2.0.0,isort==5.12.0,lazy-object-proxy==1.9.0,mccabe==0.6.1,mpmath==1.3.0,mypy-extensions==1.0.0,numpy==1.26.0,packaging==23.1,pathspec==0.11.2,pbr==5.11.1,pip==23.2.1,platformdirs==3.10.0,pluggy==0.13.1,ply==3.11,psutil==5.9.5,py==1.11.0,pycparser==2.21,pygame==2.1.2,pylint==2.9.5,pyspnego==0.9.2,pytest==6.2.4,python-constraint==1.4.0,python-dateutil==2.8.2,qiskit==0.44.1,qiskit-aer==0.10.4,qiskit-ibmq-provider==0.19.1,qiskit-ignis==0.7.0,qiskit-terra==0.25.1,requests==2.31.0,requests-ntlm==1.2.0,retworkx==0.13.1,rustworkx==0.13.1,scipy==1.11.2,setuptools==68.2.0,six==1.16.0,stevedore==5.1.0,symengine==0.9.2,sympy==1.12,toml==0.10.2,tomli==2.0.1,tox==3.24.0,tweedledum==1.1.1,typing_extensions==4.8.0,urllib3==2.0.5,virtualenv==20.24.5,websocket-client==1.6.3,websockets==11.0.3,wheel==0.41.2,wrapt==1.12.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = ""
qiskit_version = "py39: astroid==2.6.6,attrs==23.1.0,black==22.3.0,certifi==2023.7.22,cffi==1.15.1,charset-normalizer==3.2.0,click==8.1.7,coverage==5.5,cryptography==41.0.4,dill==0.3.7,distlib==0.3.7,filelock==3.12.4,idna==3.4,iniconfig==2.0.0,isort==5.12.0,lazy-object-proxy==1.9.0,mccabe==0.6.1,mpmath==1.3.0,mypy-extensions==1.0.0,numpy==1.26.0,packaging==23.1,pathspec==0.11.2,pbr==5.11.1,pip==23.2.1,platformdirs==3.10.0,pluggy==0.13.1,ply==3.11,psutil==5.9.5,py==1.11.0,pycparser==2.21,pygame==2.1.2,pylint==2.9.5,pyspnego==0.9.2,pytest==6.2.4,python-constraint==1.4.0,python-dateutil==2.8.2,qiskit==0.44.1,qiskit-aer==0.10.4,qiskit-ibmq-provider==0.19.1,qiskit-ignis==0.7.0,qiskit-terra==0.25.1,requests==2.31.0,requests-ntlm==1.2.0,retworkx==0.13.1,rustworkx==0.13.1,scipy==1.11.2,setuptools==68.2.0,six==1.16.0,stevedore==5.1.0,symengine==0.9.2,sympy==1.12,toml==0.10.2,tomli==2.0.1,tox==3.24.0,tweedledum==1.1.1,typing_extensions==4.8.0,urllib3==2.0.5,virtualenv==20.24.5,websocket-client==1.6.3,websockets==11.0.3,wheel==0.41.2,wrapt==1.12.1"
timestamp = 1695211416.922667

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = "py39: astroid==2.6.6,attrs==23.1.0,black==22.3.0,certifi==2023.7.22,cffi==1.15.1,charset-normalizer==3.2.0,click==8.1.7,coverage==5.5,cryptography==41.0.4,dill==0.3.7,distlib==0.3.7,filelock==3.12.4,idna==3.4,iniconfig==2.0.0,isort==5.12.0,lazy-object-proxy==1.9.0,mccabe==0.6.1,mpmath==1.3.0,mypy-extensions==1.0.0,numpy==1.26.0,packaging==23.1,pathspec==0.11.2,pbr==5.11.1,pip==23.2.1,platformdirs==3.10.0,pluggy==0.13.1,ply==3.11,psutil==5.9.5,py==1.11.0,pycparser==2.21,pygame==2.1.2,pylint==2.9.5,pyspnego==0.9.2,pytest==6.2.4,python-constraint==1.4.0,python-dateutil==2.8.2,qiskit==0.36.1,qiskit-aer==0.10.4,qiskit-ibmq-provider==0.19.1,qiskit-ignis==0.7.0,qiskit-terra==0.20.1,requests==2.31.0,requests-ntlm==1.2.0,retworkx==0.13.1,rustworkx==0.13.1,scipy==1.11.2,setuptools==68.2.0,six==1.16.0,stevedore==5.1.0,symengine==0.10.0,sympy==1.12,toml==0.10.2,tomli==2.0.1,tox==3.24.0,tweedledum==1.1.1,typing_extensions==4.8.0,urllib3==2.0.5,virtualenv==20.24.5,websocket-client==1.6.3,websockets==11.0.3,wheel==0.41.2,wrapt==1.12.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = ""
qiskit_version = "py39: astroid==2.6.6,attrs==23.1.0,black==22.3.0,certifi==2023.7.22,cffi==1.15.1,charset-normalizer==3.2.0,click==8.1.7,coverage==5.5,cryptography==41.0.4,dill==0.3.7,distlib==0.3.7,filelock==3.12.4,idna==3.4,iniconfig==2.0.0,isort==5.12.0,lazy-object-proxy==1.9.0,mccabe==0.6.1,mpmath==1.3.0,mypy-extensions==1.0.0,numpy==1.26.0,packaging==23.1,pathspec==0.11.2,pbr==5.11.1,pip==23.2.1,platformdirs==3.10.0,pluggy==0.13.1,ply==3.11,psutil==5.9.5,py==1.11.0,pycparser==2.21,pygame==2.1.2,pylint==2.9.5,pyspnego==0.9.2,pytest==6.2.4,python-constraint==1.4.0,python-dateutil==2.8.2,qiskit==0.36.1,qiskit-aer==0.10.4,qiskit-ibmq-provider==0.19.1,qiskit-ignis==0.7.0,qiskit-terra==0.20.1,requests==2.31.0,requests-ntlm==1.2.0,retworkx==0.13.1,rustworkx==0.13.1,scipy==1.11.2,setuptools==68.2.0,six==1.16.0,stevedore==5.1.0,symengine==0.10.0,sympy==1.12,toml==0.10.2,tomli==2.0.1,tox==3.24.0,tweedledum==1.1.1,typing_extensions==4.8.0,urllib3==2.0.5,virtualenv==20.24.5,websocket-client==1.6.3,websockets==11.0.3,wheel==0.41.2,wrapt==1.12.1"
timestamp = 1695211418.435051

[configuration]
dependencies_files = [ "requirements.txt", "requirements-dev.txt",]
extra_dependencies = [ "pytest",]
tests_command = [ "pytest",]
styles_check_command = [ "pylint -rn qpong tests",]
coverages_check_command = [ "coverage3 run -m pytest", "coverage3 report --fail-under=80",]

[configuration.language]
name = "python"
versions = [ "3.9",]
