name = "qtcodes"
url = "https://github.com/yaleqc/qtcodes"
description = "Qiskit Topological Codes"
licence = "Apache 2.0"
contact_info = ""
alternatives = ""
labels = [ "plugin",]
created_at = 1678827878.827901
updated_at = 1678827878.827902
tier = "Community"
skip_tests = false
stars = 82
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit-terra"
package_version = "0.24.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044195"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
terra_version = "0.24.0"
timestamp = 1691242060.393649

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044129"
terra_version = "0.23.2"
timestamp = 1691242060.393655

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044129"
terra_version = "0.23.2"
timestamp = 1691242060.393659

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044094"
terra_version = "0.23.2"
timestamp = 1691242060.393663

[[styles_results]]
passed = false
style_type = "pylint"

[[coverages_results]]
passed = false
coverage_type = ""

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.20.2"
terra_version = "0.20.2"
timestamp = 1691242060.393676

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit-terra"
package_version = "0.21.0"
terra_version = "0.21.0"
timestamp = 1691242060.39368

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.20.2"
terra_version = "0.20.2"
timestamp = 1691242060.393683

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.21.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548269"
terra_version = "0.21.0"
timestamp = 1691242060.393686

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.21.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2617548269"
terra_version = "0.21.0"
timestamp = 1691242060.39369

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.21.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121068"
terra_version = "0.21.1"
timestamp = 1691242060.393694

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.21.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/2824121068"
terra_version = "0.21.1"
timestamp = 1691242060.393697

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180919232"
package_commit_hash = "53e215c31cf3aea51a623dc22883ac92fe74d0b9"
terra_version = "0.22.0"
timestamp = 1691242060.393701

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.21.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3180919153"
terra_version = "0.21.2"
timestamp = 1691242060.393704

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.21.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3225637904"
terra_version = "0.21.2"
timestamp = 1691242060.393708

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368223904"
terra_version = "0.22.0"
timestamp = 1691242060.393711

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3368223902"
terra_version = "0.22.0"
timestamp = 1691242060.393714

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521950844"
terra_version = "0.22.2"
timestamp = 1691242060.393718

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3521950941"
terra_version = "0.22.2"
timestamp = 1691242060.393721

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937701356"
package_commit_hash = "af0b2220b75fd5cf3980576b1a31f9c4ceb9f99f"
terra_version = "0.23.0"
timestamp = 1691242060.393725

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937701333"
terra_version = "0.22.3"
timestamp = 1691242060.393728

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.3"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3937701250"
terra_version = "0.22.3"
timestamp = 1691242060.393732

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.22.4"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/3994625932"
terra_version = "0.22.4"
timestamp = 1691242060.393735

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052481542"
terra_version = "0.23.0"
timestamp = 1691242060.393738

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4052481466"
terra_version = "0.23.0"
timestamp = 1691242060.393742

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231020538"
terra_version = "0.23.1"
timestamp = 1691242060.393745

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4231020492"
terra_version = "0.23.1"
timestamp = 1691242060.393748

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044129"
terra_version = "0.23.2"
timestamp = 1691242060.393752

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit-terra"
package_version = "0.24.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044195"
package_commit_hash = "3005806e48da61f235742bb365e251bce37452bd"
terra_version = "0.24.0"
timestamp = 1691242060.393756

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit-terra"
package_version = "0.23.2"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/4414044094"
terra_version = "0.23.2"
timestamp = 1691242060.393759

[configuration]
dependencies_files = []
extra_dependencies = [ "qiskit", "coverage", "pylint", "numpy", "matplotlib>=3.3.0", "retworkx>=0.10.0", "tqdm", "pylatexenc", "IPython", "mypy", "black", "pytest",]
tests_command = [ "python -m unittest",]
styles_check_command = [ "pylint -rn qtcodes",]
coverages_check_command = [ "coverage3 -m pytest", "coverage3 report --fail-under=80",]

[configuration.language]
name = "python"
versions = [ "3.6",]
