name = "Quantum-Glasses"
url = "https://github.com/Jayshah25/Quantum-Glasses"
description = "Visualise the effects of Single Qubit Gates on a Qubit via Bloch Sphere Simulation in a Tkinter Software."
licence = "Apache License 2.0"
contact_info = "shahj097@gmail.com"
alternatives = "The only alternative is to code up a circuit (qiskit.QuantumCircuit) and pass the circuit to visualize_transition from qiskit.visualization. Quantum Glasses implementation wraps all of this into a simple, easy to use Tkinter Software."
affiliations = "_No response_"
labels = [ "Visualization",]
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 6
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6233498114"
package_commit_hash = "2d3632fee633413bb1883e411d1a26f76fc54e92"
qiskit_version = "0.45.0"
timestamp = 1695114896.31468

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6233498114"
qiskit_version = "0.44.1"
timestamp = 1695114954.215711

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6233498114"
qiskit_version = "0.44.1"
timestamp = 1695114564.047252

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6233498114"
qiskit_version = "0.44.1"
timestamp = 1695114950.720991

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6233498114"
qiskit_version = "0.44.1"
timestamp = 1695114950.720991

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6233498114"
package_commit_hash = "2d3632fee633413bb1883e411d1a26f76fc54e92"
qiskit_version = "0.45.0"
timestamp = 1695114896.31468

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6233498114"
qiskit_version = "0.44.1"
timestamp = 1695114564.047252

