name = "SSVQE"
url = "https://github.com/JoelHBierman/SSVQE"
description = "The SSVQE algorithm (https://arxiv.org/abs/1810.09434) is a generalization of VQE to find low-lying eigenstates of a Hermitian operator. This specific implementation of SSVQE carries out one optimization procedure using weights."
licence = "Apache License 2.0"
contact_info = "joel.bierman@duke.edu"
alternatives = "_No response_"
affiliations = "Duke University"
labels = [ "Algorithms", "Chemistry",]
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 0
[[tests_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6247472618"
package_commit_hash = ""
qiskit_version = ""
timestamp = 1695207116.184607

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6247472618"
qiskit_version = ""
timestamp = 1695207119.10331

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6247472618"
package_commit_hash = ""
qiskit_version = ""
timestamp = 1695207118.131166

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6247472618"
package_commit_hash = ""
qiskit_version = ""
timestamp = 1695207120.072029

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6247472618"
package_commit_hash = ""
qiskit_version = ""
timestamp = 1695207116.184607

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6247472618"
package_commit_hash = ""
qiskit_version = ""
timestamp = 1695207118.131166

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6247472618"
package_commit_hash = ""
qiskit_version = ""
timestamp = 1695207120.072029

