name = "SSVQE"
url = "https://github.com/JoelHBierman/SSVQE"
description = "The SSVQE algorithm (https://arxiv.org/abs/1810.09434) is a generalization of VQE to find low-lying eigenstates of a Hermitian operator. This specific implementation of SSVQE carries out one optimization procedure using weights."
licence = "Apache License 2.0"
contact_info = "joel.bierman@duke.edu"
alternatives = "_No response_"
affiliations = "Duke University"
labels = [ "Algorithms", "Chemistry",]
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 0
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "development"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6261555033/job/17001890934"
package_commit_hash = "d55965993d1d85c1a958a1ea7fbefe94917b061e"
qiskit_version = "development"
timestamp = 1695299622.314441

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6261555033/job/17001891189"
qiskit_version = "0.44.1"
timestamp = 1695299616.601515

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6261555033/job/17001891189"
package_commit_hash = ""
qiskit_version = "0.44.1"
timestamp = 1695299615.764728

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.25.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6261555033/job/17001892008"
package_commit_hash = ""
qiskit_version = "0.25.1"
timestamp = 1695299579.795149

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.25.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6261555033/job/17001892008"
package_commit_hash = ""
qiskit_version = "0.25.1"
timestamp = 1695299579.795149

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6261555033/job/17001891189"
package_commit_hash = ""
qiskit_version = "0.44.1"
timestamp = 1695299615.764728

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "development"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6261555033/job/17001890934"
package_commit_hash = "d55965993d1d85c1a958a1ea7fbefe94917b061e"
qiskit_version = "development"
timestamp = 1695299622.314441

