name = "SSVQE"
url = "https://github.com/JoelHBierman/SSVQE"
description = "The SSVQE algorithm (https://arxiv.org/abs/1810.09434) is a generalization of VQE to find low-lying eigenstates of a Hermitian operator. This specific implementation of SSVQE carries out one optimization procedure using weights."
licence = "Apache License 2.0"
contact_info = "joel.bierman@duke.edu"
alternatives = "_No response_"
affiliations = "Duke University"
labels = [ "Algorithms", "Chemistry",]
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 0
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "development"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6261950053/job/17003091176"
package_commit_hash = "d55965993d1d85c1a958a1ea7fbefe94917b061e"
qiskit_version = "development"
timestamp = 1695301757.443219

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6261950053/job/17003091471"
qiskit_version = "0.44.1"
timestamp = 1695301751.425509

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6261950053/job/17003091471"
package_commit_hash = ""
qiskit_version = "0.44.1"
timestamp = 1695301750.553485

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.25.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6261950053/job/17003091719"
package_commit_hash = ""
qiskit_version = "0.25.1"
timestamp = 1695301714.0405

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.25.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6261950053/job/17003091719"
package_commit_hash = ""
qiskit_version = "0.25.1"
timestamp = 1695301714.0405

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6261950053/job/17003091471"
package_commit_hash = ""
qiskit_version = "0.44.1"
timestamp = 1695301750.553485

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "development"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6261950053/job/17003091176"
package_commit_hash = "d55965993d1d85c1a958a1ea7fbefe94917b061e"
qiskit_version = "development"
timestamp = 1695301757.443219

