name = "SSVQE"
url = "https://github.com/JoelHBierman/SSVQE"
description = "The SSVQE algorithm (https://arxiv.org/abs/1810.09434) is a generalization of VQE to find low-lying eigenstates of a Hermitian operator. This specific implementation of SSVQE carries out one optimization procedure using weights."
licence = "Apache License 2.0"
contact_info = "joel.bierman@duke.edu"
alternatives = "_No response_"
affiliations = "Duke University"
labels = [ "Algorithms", "Chemistry",]
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 0
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "development"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6251363251/job/16972342167"
package_commit_hash = "22b94a139e89917d0291f3f1f1c598b38b53eff4"
qiskit_version = "development"
timestamp = 1695227525.744528

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6251363251/job/16972342453"
qiskit_version = "0.44.1"
timestamp = 1695227520.702721

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6251363251/job/16972342453"
package_commit_hash = ""
qiskit_version = "0.44.1"
timestamp = 1695227519.930243

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.25.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6251363251/job/16972342727"
package_commit_hash = ""
qiskit_version = "0.25.1"
timestamp = 1695227488.708341

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.25.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6251363251/job/16972342727"
package_commit_hash = ""
qiskit_version = "0.25.1"
timestamp = 1695227488.708341

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6251363251/job/16972342453"
package_commit_hash = ""
qiskit_version = "0.44.1"
timestamp = 1695227519.930243

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "development"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6251363251/job/16972342167"
package_commit_hash = "22b94a139e89917d0291f3f1f1c598b38b53eff4"
qiskit_version = "development"
timestamp = 1695227525.744528

