name = "SSVQE"
url = "https://github.com/JoelHBierman/SSVQE"
description = "The SSVQE algorithm (https://arxiv.org/abs/1810.09434) is a generalization of VQE to find low-lying eigenstates of a Hermitian operator. This specific implementation of SSVQE carries out one optimization procedure using weights."
licence = "Apache License 2.0"
contact_info = "joel.bierman@duke.edu"
alternatives = "_No response_"
affiliations = "Duke University"
labels = [ "Algorithms", "Chemistry",]
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 0
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6233498981"
package_commit_hash = "2d3632fee633413bb1883e411d1a26f76fc54e92"
qiskit_version = "0.45.0"
timestamp = 1695114991.456783

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6233498981"
qiskit_version = "0.44.1"
timestamp = 1695115071.794078

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6233498981"
qiskit_version = "0.44.1"
timestamp = 1695114644.213464

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6233498981"
qiskit_version = "0.44.1"
timestamp = 1695115070.675836

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6233498981"
qiskit_version = "0.44.1"
timestamp = 1695114644.213464

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6233498981"
package_commit_hash = "2d3632fee633413bb1883e411d1a26f76fc54e92"
qiskit_version = "0.45.0"
timestamp = 1695114991.456783

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6233498981"
qiskit_version = "0.44.1"
timestamp = 1695115070.675836

