name = "My test project"
url = "https://github.com/frankharkins/test-project"
description = "Hello"
licence = "Apache License 2.0"
labels = []
website = "https://my-test-website.com"
group = "transpiler_plugin"
