name = "vqls-prototype"
url = "https://github.com/QuantumApplicationLab/vqls-prototype"
description = "The Variational Quantum Linear Solver (VQLS) uses an optimization approach to solve linear systems of equations. The vqls-prototype allows to easily setup and deploy a VQLS instance on different backends through the use of qiskit primitives and the runtime library"
licence = "Apache License 2.0"
contact_info = "nicolas.gm.renaud@gmail.com"
alternatives = "The prototype builds on the qiskit-textbook chapter and tutorial. The prototype allows to use the primitives and use different cost function and test circuits to optimize the parameters."
affiliations = "Netherlands eScience Center @ Quantum Application Lab, Amsterdam NL"
labels = [ "Algorithms", "Optimization",]
created_at = 1683906067.55753
updated_at = 1683906067.557535
tier = "Community"
styles_results = []
coverages_results = []
skip_tests = false
stars = 2
[[tests_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = "01bb111cfa706658134c4481a354133bc5326f24"
qiskit_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__"
timestamp = 1695211482.685567

[[tests_results]]
passed = true
test_type = "last passing version"
package = "qiskit"
package_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
qiskit_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__"
timestamp = 1695211485.296581

[[tests_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = ""
qiskit_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__"
timestamp = 1695211484.396037

[[tests_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = ""
qiskit_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__"
timestamp = 1695211486.104286

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = "0.44.1"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936779850"
qiskit_version = "0.44.1"
timestamp = 1692695887.724092

[[historical_test_results]]
passed = true
test_type = "development"
package = "qiskit"
package_version = "0.45.0"
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936779850"
package_commit_hash = "0b51250e219ca303654fc28a318c21366584ccd3"
qiskit_version = "0.45.0"
timestamp = 1692695887.724096

[[historical_test_results]]
passed = false
test_type = "standard"
package = "qiskit"
package_version = ""
logs_link = "https://github.com/qiskit-community/ecosystem/actions/runs/5936779850"
qiskit_version = ""
timestamp = 1692695887.580608

[[historical_test_results]]
passed = false
test_type = "development"
package = "qiskit"
package_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = "01bb111cfa706658134c4481a354133bc5326f24"
qiskit_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__"
timestamp = 1695211482.685567

[[historical_test_results]]
passed = true
test_type = "stable"
package = "qiskit"
package_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = ""
qiskit_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__"
timestamp = 1695211484.396037

[[historical_test_results]]
passed = true
test_type = "standard"
package = "qiskit"
package_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__"
logs_link = "https://github.com/frankharkins/ecosystem/actions/runs/6248125621"
package_commit_hash = ""
qiskit_version = ".pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__"
timestamp = 1695211486.104286

