name: Simplified testing

on:
  workflow_call:
    inputs:
      repo_name:
        description: "GitHub repository owner-name/repo-name"
        type: string
        required: true
      test_type:
        description: "'standard', 'stable', or 'dev'"
        type: string
        required: true

  workflow_dispatch:
    inputs:
      repo_name:
        description: "GitHub repository owner-name/repo-name"
        type: string
        required: true
      test_type:
        description: "Type of test to run"
        required: true 
        default: 'standard'
        type: choice
        options:
          - standard
          - stable
          - development

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo_name }}

      - name: Detect repo settings
        run: |
          if [ -e ecosystem.json ]; then echo "HAS_ECOSYSTEM_JSON=true" >> "$GITHUB_ENV"; fi
          if [ -e tox.ini ]; then echo "HAS_TOX_INI=true" >> "$GITHUB_ENV"; fi
          echo "REQUIREMENTS_FILES=$(ls *requirements*.txt | xargs)" >> "$GITHUB_ENV"

      - name: Create default tox.ini
        if: ${{ env.HAS_TOX_INI != 'true' }}
        run: |
          echo "[tox]
          env_list = py39
          skipsdist = True

          [testenv]
          usedevelop = true
          deps =
            pytest
          $(for FILE in $REQUIREMENTS_FILES; do echo "  -r$FILE"; done)
          commands =
              python -m unittest -v
          " > tox.ini
          echo "Created default tox.ini:"
          cat tox.ini | xargs echo -e

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up standard environment
        run: |
          pip install tox
          tox exec -epy39 -- python -c ""  # Empty command to force tox setup

      - name: Force install development qiskit
        if: ${{ inputs.test_type == 'development' }}
        run: |
          tox exec -epy39 -- pip install git+https://github.com/Qiskit/qiskit
          
      - name: Run tests
        run: |
          tox -epy39


